name: "Revert Development Mode"
description: "Runs RevertDevelopmentMode.ps1 to restore the repository after development."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run RevertDevelopmentMode.ps1
      shell: pwsh
      run: |
        & "${{ github.action_path }}/RevertDevelopmentMode.ps1" \
          -MinimumSupportedLVVersion "${{ inputs.minimum_supported_lv_version }}" \
          -RelativePath "${{ inputs.relative_path }}"
inputs:
  minimum_supported_lv_version:
    description: 'LabVIEW major version (2020-2025)'
    required: false
    default: '2021'
  relative_path:
    description: 'Workspace root path'
    required: false
